version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: carritoIA         
      MYSQL_USER: admin                 
      MYSQL_PASSWORD: root         
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data:
    driver: local
